### PR TITLE
Fix PrintProviderField to work with textboxes

### PR DESCRIPTION
**Pull request by geographika**
With associated test. See issue #363

### CODE REVIEW

**Comment by chrismayer** [comment]
Hi @geographika,
thanks a lot for your contribution. For me this looks very good.  But I would like to have a second opinion on this. Maybe @weskamm or @marcjansen can have quick look?

**Comment by marcjansen** [comment]
his looks good to me, @geographika and @chrismayer. I may have asked earlier, but do we have the CLA from you @geographika?

**Comment by chrismayer** [comment]
I wrote him yesterday because of the CLA topic. Answer outstanding.

**Comment by chrismayer** [comment]
The signed CLA of @geographika has been sent to the PSC.

**Pull request merged**
