### PR TITLE
Use CSS styling to paint popup anchors

### PR DESCRIPTION
**Pull request by bentrm**

### CODE REVIEW

**Comment by marcjansen** [comment]
Any news here? Anybody willing to tackle this again? /cc @chrismayer, @bentrm

**Comment by bentrm** [comment]
I checked this again and did not find a consistent way to calculate the needed offset that take into account the shortcomings of IE8. Maybe this is different with ExtJS 5 but I didn't check that yet. The only thing I can suggest at this point is to provide this as an optional way of styling popups for applications that don't need to be backwards compatible with IE < 9.

**Comment by marcjansen** [comment]
So @bentrm will you then be able to change this so that newer browsers get the  CSS-only triangles, while old IE will get the image one? I'd favor that solution. For the planned v2.1.0 I don't think IE 8 will be supported.

**Comment by bentrm** [comment]
> For the planned v2.1.0 I don't think IE 8 will be supported.

Since we're well into 2.1 now I updated this PR:

* includes stylesheets for ExtJS 4 and 5 themes
* popup example loads the required CSS via the theme parameter
* anchor images have been removed completely

Would be nice for someone to shim in an review. Thanks!

**Comment by marcjansen** [comment]
Code looks very good to me. If you confirm it works, please merge!

**Pull request merged**
