### PR TITLE
Correct copyright date

### PR DESCRIPTION
**Pull request by chrismayer**
Title says it all...

### CODE REVIEW

**Comment by bartvde** [comment]
I wonder if we can just do -present like Facebook does on React?

**Comment by marcjansen** [comment]
This one can be merged. I'd not be against 'to present'

**Comment by chrismayer** [comment]
I'm also :+1:  for ``- present``. Is it OK for you if I rebase this or should I do another PR?

**Comment by bartvde** [comment]
rebase is fine, TIA

**Comment by marcjansen** [comment]
Please merge this, Chris. Thanks again

**Pull request merged**
