### PR TITLE
Bumpin copyright date

### PR DESCRIPTION
**Pull request by chrismayer**
Title says it all...

### CODE REVIEW

**Comment by marcjansen** [comment]
Thanks, @chrismayer.

I also think we should have this in the 2.0.3 release, right?  But we surely don't want to change that tag. Which means we'd need another release.

What does everybody think of the following approach:

* merge this into the `master`-branch,
* merge this into the `v2.0.x-maintenance`-branch (I am unsure about how to do this, shall we just cherry-pick 8d9203b?)
* release a v2.0.4 (or v2.0.3.1?) from the `v2.0.x-maintenance`-branch

Any other ideas or opinions?

/cc @bartvde @juliensam

**Comment by bartvde** [comment]
I would not do a new release just because of copyright dates. I'd just merge this and we'll have it in the next release?

**Comment by marcjansen** [comment]
I do not have a strong opinion, and could live with that.

**Comment by weskamm** [comment]
same opinion as bartvde, i think no new release is necessary, but leave it up to you

**Comment by marcjansen** [comment]
Cherry picked to `v2.0.x-maintenance` as 56548318963c2275619222e10370897e90f79a2d

Thanks to everyone.

**Pull request merged**
