### PR TITLE
Adopt Sencha Cmd package structure and SASS styling

### PR DESCRIPTION
**Pull request by bentrm**
These changes make the repository compatible to be used as a package in a Sencha Cmd workspace. All that is required by the user is to clone the repo into the workspaces package directory and add `"requires": [ "GeoExt" ]` to the apps `app.json`.

If the repository has been cloned into a folder named `GeoExt` (the packages name as defined in `.sencha/package/sencha.cfg`) an additional Ext.Loader configuration is not needed for the application to find appropriate class definitions.

Additionally, a basic SASS structure has been added and the existing CSS files have been migrated. That means changing the applications theme by adding something like `"theme": "ext-theme-neptune"` to app.json will catch up the required styles of the GeoExt package.

### CODE REVIEW

**Comment by marcjansen** [comment]
Hey @bentrm are you planning on working on this again?

**Comment by bentrm** [comment]
I will make time for this but if you'd like to clean up the pending PRs screen feel free to close until then.

**Comment by marcjansen** [comment]
We can leave it open, no problem. I just wanted to see if somebody is still working on this.

**Comment by bentrm** [comment]
This PR is superseded by #350.

**Pull request closed without merging**
