### PR TITLE
Switch to OpenLayers 3 for the mapping engine

### PR DESCRIPTION
**Pull request by bartvde**
Experimental
Work in progress

### CODE REVIEW

**Comment by thiagogcm** [comment]
How's it going ?

**Comment by weskamm** [comment]
@thiagogcm: Have a look over here: https://github.com/KaiVolland/geoext3

**Comment by bentrm** [comment]
@bartvde, do you want to keep this open as a reminder or may we close the PR?

**Comment by bartvde** [comment]
Let's close

**Pull request closed without merging**
